version: '3'

services:
  alibaba_postgresql:
    image: postgres:12
    container_name: alibaba_postgresql
    volumes:
     - alibaba_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
     - "5432:5432"
    networks:
     - alibaba_network

volumes:
  alibaba_postgresql:
    external: true

networks:
  alibaba_network:
    external: true